// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpsForge.Infrastructure.Persistence.Contexts;

#nullable disable

namespace OpsForge.Infrastructure.Migrations
{
    [DbContext(typeof(MachineContext))]
    [Migration("20251219153540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Machines")
                .HasAnnotation("Deployment:Criticality", "Tier 1 - Production Critical")
                .HasAnnotation("Deployment:SchemaPrefix", "prod_mach")
                .HasAnnotation("Documentation:Description", "The Machine Context manages all static and dynamic data related to production floor machines, including configuration and operational metrics.")
                .HasAnnotation("Documentation:OwnerTeam", "Manufacturing Excellence (MEx)")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpsForge.Domain.Entities.AggregateMaintenance.MaintenanceOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MaintenanceOrder", "Machines");
                });

            modelBuilder.Entity("OpsForge.Domain.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Code")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineStatus")
                        .HasColumnType("int");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductionLine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code");

                    b.ToTable("Machine", "Machines");

                    b.HasDiscriminator<string>("MachineType").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine", b =>
                {
                    b.HasBaseType("OpsForge.Domain.Entities.Machine");

                    b.Property<DateTime?>("Actuators_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ControlUnit_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConveyorSystem_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CoolingSystem_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HMI_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PLC_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SafetyGuards_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Sensors_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ToolChanger_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WeldingHead_LastReplaced")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("Actuators", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.Actuators#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Actuators_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Actuators_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Actuators_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ControlUnit", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.ControlUnit#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ControlUnit_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ControlUnit_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ControlUnit_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ConveyorSystem", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.ConveyorSystem#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ConveyorSystem_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ConveyorSystem_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ConveyorSystem_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("CoolingSystem", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.CoolingSystem#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CoolingSystem_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CoolingSystem_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CoolingSystem_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("HMI", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.HMI#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HMI_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HMI_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HMI_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PLC", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.PLC#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PLC_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PLC_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PLC_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SafetyGuards", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.SafetyGuards#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SafetyGuards_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SafetyGuards_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SafetyGuards_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Sensors", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.Sensors#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Sensors_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Sensors_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Sensors_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ToolChanger", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.ToolChanger#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ToolChanger_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ToolChanger_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ToolChanger_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("WeldingHead", "OpsForge.Domain.Entities.AggregateMachine.Machines.AutomaticMeldingMachine.WeldingHead#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WeldingHead_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WeldingHead_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WeldingHead_SerialNumber");
                        });

                    b.HasDiscriminator().HasValue("Automatic");
                });

            modelBuilder.Entity("OpsForge.Domain.Entities.AggregateMachine.Machines.CncMillingMachine", b =>
                {
                    b.HasBaseType("OpsForge.Domain.Entities.Machine");

                    b.Property<DateTime?>("BallScrews_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CoolantPump_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LinearGuides_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MainSpindle_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ToolMagazine_LastReplaced")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("BallScrews", "OpsForge.Domain.Entities.AggregateMachine.Machines.CncMillingMachine.BallScrews#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BallScrews_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BallScrews_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BallScrews_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("CoolantPump", "OpsForge.Domain.Entities.AggregateMachine.Machines.CncMillingMachine.CoolantPump#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CoolantPump_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CoolantPump_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CoolantPump_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LinearGuides", "OpsForge.Domain.Entities.AggregateMachine.Machines.CncMillingMachine.LinearGuides#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LinearGuides_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LinearGuides_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LinearGuides_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MainSpindle", "OpsForge.Domain.Entities.AggregateMachine.Machines.CncMillingMachine.MainSpindle#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MainSpindle_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MainSpindle_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MainSpindle_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ToolMagazine", "OpsForge.Domain.Entities.AggregateMachine.Machines.CncMillingMachine.ToolMagazine#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ToolMagazine_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ToolMagazine_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ToolMagazine_SerialNumber");
                        });

                    b.HasDiscriminator().HasValue("CNC");
                });

            modelBuilder.Entity("OpsForge.Domain.Entities.AggregateMachine.Machines.HydraulicPress", b =>
                {
                    b.HasBaseType("OpsForge.Domain.Entities.Machine");

                    b.Property<DateTime?>("HydraulicCylinder_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HydraulicOilTank_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HydraulicPump_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProportionalValves_LastReplaced")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("HydraulicCylinder", "OpsForge.Domain.Entities.AggregateMachine.Machines.HydraulicPress.HydraulicCylinder#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicCylinder_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicCylinder_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicCylinder_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("HydraulicOilTank", "OpsForge.Domain.Entities.AggregateMachine.Machines.HydraulicPress.HydraulicOilTank#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicOilTank_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicOilTank_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicOilTank_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("HydraulicPump", "OpsForge.Domain.Entities.AggregateMachine.Machines.HydraulicPress.HydraulicPump#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicPump_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicPump_Model");

                            b1.Property<string>("SerialNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicPump_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ProportionalValves", "OpsForge.Domain.Entities.AggregateMachine.Machines.HydraulicPress.ProportionalValves#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProportionalValves_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProportionalValves_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProportionalValves_SerialNumber");
                        });

                    b.ToTable("Machine", "Machines", t =>
                        {
                            t.Property("HydraulicPump_LastReplaced")
                                .HasColumnName("HydraulicPress_HydraulicPump_LastReplaced");
                        });

                    b.HasDiscriminator().HasValue("Hydraulic");
                });

            modelBuilder.Entity("OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine", b =>
                {
                    b.HasBaseType("OpsForge.Domain.Entities.Machine");

                    b.Property<DateTime?>("ClampingUnit_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FumeExtractionSystem_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HydraulicPump_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InjectionMold_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InjectionUnit_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MaterialHopperDryer_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PositionerTable_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PowerSourceWelder_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WeldingTorch_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WireFeeder_LastReplaced")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("ClampingUnit", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.ClampingUnit#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ClampingUnit_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ClampingUnit_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ClampingUnit_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FumeExtractionSystem", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.FumeExtractionSystem#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FumeExtractionSystem_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FumeExtractionSystem_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FumeExtractionSystem_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("HydraulicPump", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.HydraulicPump#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicPump_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicPump_Model");

                            b1.Property<string>("SerialNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HydraulicPump_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("InjectionMold", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.InjectionMold#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("InjectionMold_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("InjectionMold_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("InjectionMold_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("InjectionUnit", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.InjectionUnit#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("InjectionUnit_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("InjectionUnit_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("InjectionUnit_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MaterialHopperDryer", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.MaterialHopperDryer#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MaterialHopperDryer_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MaterialHopperDryer_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MaterialHopperDryer_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PositionerTable", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.PositionerTable#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PositionerTable_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PositionerTable_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PositionerTable_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PowerSourceWelder", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.PowerSourceWelder#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PowerSourceWelder_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PowerSourceWelder_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PowerSourceWelder_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("WeldingTorch", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.WeldingTorch#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WeldingTorch_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WeldingTorch_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WeldingTorch_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("WireFeeder", "OpsForge.Domain.Entities.AggregateMachine.Machines.InjectionMeldingMachine.WireFeeder#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WireFeeder_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WireFeeder_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WireFeeder_SerialNumber");
                        });

                    b.HasDiscriminator().HasValue("Injection");
                });

            modelBuilder.Entity("OpsForge.Domain.Entities.AggregateMachine.Machines.RoboticAssemblyLine", b =>
                {
                    b.HasBaseType("OpsForge.Domain.Entities.Machine");

                    b.Property<DateTime?>("ConveyorBelt_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PLCHMIController_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PneumaticGrippers_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RobotArmJoint_LastReplaced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisionSensors_LastReplaced")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("ConveyorBelt", "OpsForge.Domain.Entities.AggregateMachine.Machines.RoboticAssemblyLine.ConveyorBelt#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ConveyorBelt_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ConveyorBelt_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ConveyorBelt_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PLCHMIController", "OpsForge.Domain.Entities.AggregateMachine.Machines.RoboticAssemblyLine.PLCHMIController#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PLCHMIController_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PLCHMIController_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PLCHMIController_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PneumaticGrippers", "OpsForge.Domain.Entities.AggregateMachine.Machines.RoboticAssemblyLine.PneumaticGrippers#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PneumaticGrippers_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PneumaticGrippers_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PneumaticGrippers_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RobotArmJoint", "OpsForge.Domain.Entities.AggregateMachine.Machines.RoboticAssemblyLine.RobotArmJoint#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RobotArmJoint_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RobotArmJoint_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RobotArmJoint_SerialNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("VisionSensors", "OpsForge.Domain.Entities.AggregateMachine.Machines.RoboticAssemblyLine.VisionSensors#SparePart", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("VisionSensors_Brand");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("VisionSensors_Model");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("VisionSensors_SerialNumber");
                        });

                    b.HasDiscriminator().HasValue("Robotic");
                });

            modelBuilder.Entity("OpsForge.Domain.Entities.AggregateMaintenance.MaintenanceOrder", b =>
                {
                    b.HasOne("OpsForge.Domain.Entities.Machine", null)
                        .WithMany("Maintenances")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpsForge.Domain.Entities.AggregateMaintenance.MaintenanceSchedule", "Schedule", b1 =>
                        {
                            b1.Property<int>("MaintenanceOrderId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("LastMaintenanceDate")
                                .HasColumnType("datetime2");

                            b1.Property<TimeSpan>("MaintenanceInterval")
                                .HasColumnType("time");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("MaintenanceOrderId");

                            b1.ToTable("MaintenanceOrder", "Machines");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceOrderId");
                        });

                    b.OwnsMany("OpsForge.Domain.Enums.Status", "Statuses", b1 =>
                        {
                            b1.Property<int>("MaintenanceStatusId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("MaintenanceStatusId"));

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("StatusId");

                            b1.Property<int>("MaintenanceOrderId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MaintenanceStatusId");

                            b1.HasIndex("MaintenanceOrderId");

                            b1.ToTable("MaintenanceStatus", "Machines");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceOrderId");
                        });

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("OpsForge.Domain.Entities.Machine", b =>
                {
                    b.OwnsOne("OpsForge.Domain.Entities.AggregateMachine.Inventory.Inventory", "Inventory", b1 =>
                        {
                            b1.Property<int>("MachineId")
                                .HasColumnType("int");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machine", "Machines");

                            b1.ToJson("Inventory");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");

                            b1.OwnsMany("OpsForge.Domain.Entities.AggregateMachine.Machines.SparePart", "Parts", b2 =>
                                {
                                    b2.Property<int>("InventoryMachineId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<string>("Brand")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Model")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("SerialNumber")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("InventoryMachineId", "Id");

                                    b2.ToTable("Machine", "Machines");

                                    b2.ToJson("Parts");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryMachineId");
                                });

                            b1.Navigation("Parts");
                        });

                    b.OwnsOne("OpsForge.Domain.Entities.AggregateMachine.MachineSpecification", "Specification", b1 =>
                        {
                            b1.Property<int>("MachineId")
                                .HasColumnType("int");

                            b1.Property<string>("_description")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Description");

                            b1.Property<double>("_dimensions_Height")
                                .HasColumnType("float")
                                .HasColumnName("Dimension_Height");

                            b1.Property<double>("_dimensions_Length")
                                .HasColumnType("float")
                                .HasColumnName("Dimension_Length");

                            b1.Property<double>("_dimensions_Width")
                                .HasColumnType("float")
                                .HasColumnName("Dimension_Width");

                            b1.Property<string>("_manufacturer")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Manufacturer");

                            b1.Property<string>("_material")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Material");

                            b1.Property<string>("_model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Model");

                            b1.Property<double>("_powerKw")
                                .HasColumnType("float")
                                .HasColumnName("PowerKw");

                            b1.Property<double>("_voltage")
                                .HasColumnType("float")
                                .HasColumnName("Voltage");

                            b1.Property<double>("_weightKg")
                                .HasColumnType("float")
                                .HasColumnName("WeightKg");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machine", "Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("OpsForge.Domain.Entities.Machine", b =>
                {
                    b.Navigation("Maintenances");
                });
#pragma warning restore 612, 618
        }
    }
}
